'use client'

// import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import './globals.css'
import {QueryClient, QueryClientProvider} from 'react-query'
import {Providers} from './providers'

const inter = Inter({subsets: ['latin']})

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const queryClient = new QueryClient()

  return (
    <html lang="en" suppressHydrationWarning>
      <QueryClientProvider client={queryClient}>
        <body className={inter.className}>
          <Providers>{children}</Providers>
        </body>
      </QueryClientProvider>
    </html>
  )
}
